# NB: this file was automatically generated by Dynare
#     from Ramsey_b.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(6, 11);
gp = zeros(6, 11, 11);
end
return (rp, gp)
end
