# NB: this file was automatically generated by Dynare
#     from Ramsey_b.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(6, 11);
gp = zeros(6, 6, 11);
end
return (rp, gp)
end
