# NB: this file was automatically generated by Dynare
#     from RBC_abierto.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(36, 32);
gp = zeros(36, 36, 32);
end
return (rp, gp)
end
