# NB: this file was automatically generated by Dynare
#     from Ramsey_c.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(7, 12);
gp = zeros(7, 7, 12);
end
return (rp, gp)
end
