# NB: this file was automatically generated by Dynare
#     from RBC_fiscal_psi_negativo.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(24, 36);
gp = zeros(24, 46, 36);
end
return (rp, gp)
end
