# NB: this file was automatically generated by Dynare
#     from RBC_fiscal_estimacion.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(26, 39);
gp = zeros(26, 51, 39);
end
return (rp, gp)
end
