# NB: this file was automatically generated by Dynare
#     from RBC_fiscal_estimacion.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(26, 39);
gp = zeros(26, 26, 39);
end
return (rp, gp)
end
