# NB: this file was automatically generated by Dynare
#     from RBC_fiscal_anunciado.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(27, 36);
gp = zeros(27, 27, 36);
end
return (rp, gp)
end
