# NB: this file was automatically generated by Dynare
#     from NK_Cerrada.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(14, 12);
gp = zeros(14, 14, 12);
end
return (rp, gp)
end
