# NB: this file was automatically generated by Dynare
#     from RBC_fiscal.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(24, 36);
gp = zeros(24, 24, 36);
end
return (rp, gp)
end
