# NB: this file was automatically generated by Dynare
#     from Ramsey_c.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(7, 12);
gp = zeros(7, 14, 12);
end
return (rp, gp)
end
