# NB: this file was automatically generated by Dynare
#     from RBC_fiscal_anunciado.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(27, 36);
gp = zeros(27, 52, 36);
end
return (rp, gp)
end
