# NB: this file was automatically generated by Dynare
#     from NK_Abierta.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(22, 20);
gp = zeros(22, 37, 20);
end
return (rp, gp)
end
