# NB: this file was automatically generated by Dynare
#     from NK_Abierta.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(22, 20);
gp = zeros(22, 22, 20);
end
return (rp, gp)
end
